export const WORDS = [
  "Brad Pitt",
  "Lionel Messi",
  "Cristiano Ronaldo",
  "Tom Cruise",
  "Leonardo DiCaprio",
  "Michael Jordan",
  "Taylor Swift",
  "Johnny Depp",
  "Rihanna",
  "Robert Downey Jr.",
  "LeBron James",
  "Scarlett Johansson",
  "Dwayne Johnson",
  "Jennifer Lawrence",
  "Will Smith",
  "Justin Bieber",
  "David Beckham",
  "Selena Gomez",
  "Tom Hanks",
  "Miley Cyrus",
  "Mark Zuckerberg",
  "Shakira",
  "Emma Watson",
  "Elon Musk",
  "Bill Gates",
  "J.K. Rowling",
  "Vin Diesel",
  "Ed Sheeran",
  "Adele",
  "Keanu Reeves",
  "Adam Sandler",
  "Vincent van Gogh",
  "Bruce Willis",
  "Anne Hathaway",
  "Quentin Tarantino",
  "Zac Efron",
  "Timothée Chalamet",
  "Steven Spielberg",
  "Jackie Chan",
  "Ryan Reynolds",
  "Meryl Streep",
  "Harrison Ford",
  "Michael Jackson",
  "Bruno Mars",
  "Jim Carrey",
  "Amy Winehouse",
  "Al Pacino",
  "Sylvester Stallone",
  "Samuel L. Jackson",
  "Megan Fox",
  "Usain Bolt",
  "Michael Phelps",
  "Shawn Mendes",
  "Galileo Galilei",
  "Albert Einstein",
  "Pablo Picasso",
  "Walt Disney",
  "Sigmund Freud",
  "Marie Curie",
  "Frida Kahlo",
  "Stephen Hawking",
  "Neil Armstrong",
  "Salvador Dalí",
  "Winston Churchill",
  "Nelson Mandela",
  "Mahatma Gandhi",
  "Marilyn Monroe",
  "Napoleon Bonaparte",
  "Pizza",
  "Sushi",
  "Tacos",
  "Hamburguesa",
  "Pasta",
  "Ceviche",
  "Ramen",
  "Empanadas",
  "Churrasco",
  "Shawarma",
  "Risotto",
  "El Rey León",
  "La Bella y la Bestia",
  "Aladdín",
  "Frozen",
  "Mulán",
  "La Sirenita",
  "Cenicienta",
  "Blancanieves y los siete enanitos",
  "La Bella Durmiente",
  "Pocahontas",
  "Moana",
  "Enredados",
  "Hércules",
  "Tarzán",
  "El Jorobado de Notre Dame",
  "Zootopia",
  "Ralph el Demoledor",
  "Valiente",
  "La Princesa y el Sapo",
  "Lilo y Stitch",
  "Toy Story",
  "Buscando a Nemo",
  "Los Increíbles",
  "Coco",
  "Monsters, Inc.",
  "Ratatouille",
  "Cars",
  "Up: Una aventura de altura",
  "Intensa-Mente",
  "WALL-E",
  "Shrek",
  "Madagascar",
  "Kung Fu Panda",
  "Cómo entrenar a tu dragón",
  "Spirit: El corcel indomable",
  "Megamente",
  "Vecinos invasores",
  "El espanta tiburones",
  "Jack Black",
  "Titanic",
  "Avatar",
  "El Padrino",
  "Forrest Gump",
  "Star Wars",
  "La lista de Schindler",
  "Pulp Fiction",
  "El Señor de los Anillos",
  "Jurassic Park",
  "Volver al futuro",
  "Gladiador",
  "Inception",
  "Matrix",
  "El silencio de los inocentes",
  "Rocky",
  "La vida es bella",
  "El Club de la Pelea",
  "Indiana Jones",
  "E.T., el extraterrestre",
  "Los cazafantasmas",
  "Scarface",
  "Django sin cadenas",
  "Harry Potter",
  "Dune",
  "Superman",
  "Batman",
  "Spider-Man",
  "Wonder Woman",
  "Iron Man",
  "Capitan America",
  "Thor",
  "Hulk",
  "Black Panther",
  "Wolverine",
  "Aquaman",
  "The Flash",
  "Green Lantern",
  "Doctor Strange",
  "Scarlet Witch",
  "Black Widow",
  "Hawkeye",
  "Deadpool",
  "Capitana Marvel",
  "Ant-Man",
  "Joker",
  "Thanos",
  "Darth Vader",
  "Loki",
  "Magneto",
  "Cruella de Vil",
  "Doctor Octopus",
  "Venom",
  "Lex Luthor",
  "Harley Quinn",
  "Emperador Palpatine",
  "Malefica",
  "Hannibal Lecter",
  "Naruto",
  "Dragon Ball Z",
  "One Piece",
  "Death Note",
  "Attack on Titan",
  "Fullmetal Alchemist",
  "Sword Art Online",
  "One Punch Man",
  "Demon Slayer",
  "Hunter x Hunter",
  "Neon Genesis Evangelion",
  "JoJo's Bizarre Adventure",
  "Diego Maradona",
  "Carlos Gardel",
  "Evita Perón",
  "Che Guevara",
  "Luis Alberto Spinetta",
  "Juan Martín del Potro",
  "Luisana Lopilato",
  "Mauricio Macri",
  "Papa Francisco",
  "Lali Espósito",
  "Jorge Luis Borges",
  "Cristina Fernández de Kirchner",
  "Ricardo Darín",
  "Susana Giménez",
  "Gustavo Cerati",
  "Lionel Scaloni",
  "Juan Román Riquelme",
  "Mirtha Legrand",
  "Carlos Tevez",
  "Moria Casán",
  "Tini Stoessel",
  "Axel Kicillof",
  "Javier Milei",
  "Pablo Neruda",
  "Maravilla Martinez",
  "Cacho Castaña",
  "Guillermo Francella",
  "Manu Ginobili",
  "Andrés Calamaro",
  "Néstor Kirchner",
  "Martín Palermo",
  "Wanda Nara",
  "Natalia Oreiro",
  "Alberto Nisman",
  "Adrián Suar",
  "Daniel Scioli",
  "Guido Kaczka",
  "Rodrigo de la Serna",
  "Marcelo Tinelli",
  "Martín Liberman",
  "Mafalda",
  "Gaturro",
  "Mate",
  "Asado",
  "Tango",
  "Facturas",
  "Bombonera",
  "Monumental",
  "Boca",
  "Riber",
  "San Lorenzo",
  "Racing",
  "Independiente",
  "Dulce de leche",
  "Mate Cocido",
  "Alfajores",
  "Churros",
  "Flan",
  "José de San Martín",
  "Juan Manuel de Rosas",
  "Mariano Moreno",
  "Manuel Belgrano",
  "Juan Perón",
  "Hipólito Yrigoyen",
  "Raúl Alfonsín",
  "Bernardino Rivadavia",
  "Leandro N. Alem",
  "Domingo F. Sarmiento",
  "Juan Bautista Alberdi",
  "Bartolomé Mitre",
  "René Favaloro",
  "Carlos Pellegrini",
  "Martín Fierro",
  "Carlos Saul Menem",
  "Sergio Massa",
  "Luquitas Rodriguez",
  "Coscu",
  "Rebord",
  "Carlos Maslaton",
  "Stephen King",
  "Migue Granados",
  "Darío Barassi",
  "Damian Betular",
  "Julio Cortazar",
  "Axolotl",
  "Cebolla",
  "Game of Thrones",
  "Breaking Bad",
  "Friends",
  "Stranger Things",
  "The Simpsons",
  "The Office",
  "Black Mirror",
  "The Mandalorian",
  "The Crown",
  "Narcos",
  "The Big Bang Theory",
  "Peaky Blinders",
  "Vikings",
  "The Walking Dead",
  "Lost",
  "Dexter",
  "Better Call Saul",
  "The Sopranos",
  "Walter White (Breaking Bad)",
  "Jon Snow (Game Of Thrones)",
  "Michael Scott (The Office)",
  "Eleven (Stranger Things)",
  "Ross Geller (Friends)",
  "Tony Soprano (The Sopranos)",
  "Rick Grimes (The Walking Dead)",
  "Pablo Escobar",
  "Daenerys Targaryen (Game Of Thrones)",
  "Sherlock Holmes",
  "BoJack Horseman",
  "Rick and Morty",
  "Homero Simpson",
  "Marge Simpson",
  "Lisa Simpson",
  "Maggie Simpson",
  "Ned Flanders",
  "Moe Szyslak",
  "Seymour Skinner",
  "Milhouse Van Houten",
  "Peter Griffin",
  "South Park",
  "Frodo Baggins",
  "Gandalf",
  "Legolas",
  "Hobbit",
  "Gimli",
  "Sauron",
  "Aragorn",
  "Gollum",
  "Yoda",
  "Anakin",
  "Obi-Wan Kenobi",
  "Qui-Gon Jinn",
  "Darth Maul",
  "Luke Skywalker",
  "Han Solo",
  "Princess Leia",
];
